export { default as HomeSection } from './HomeSection'
export { default as AboutSection } from './AboutSection'
export { default as TechnologiesSection } from './TechnologiesSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as ContactSection } from './ContactSection'
export { default as SoonPage } from './ComingSoon'
export { default as NotFound } from './NotFound'