export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
export { default as TechnologiesPage } from './TechnologiesPage'
export { default as ProjectPage } from './ProjectPage'
export { default as NotFoundPage } from './NotFoundPage'